openapi: 3.0.0
info:
  title: Take a Pill API
  description: API для управления расписанием приема лекарств
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Локальный сервер разработки

paths:
  /schedule:
    post:
      summary: Создание нового расписания приема лекарств
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - medicine_name
                - frequency
                - duration
              properties:
                user_id:
                  type: string
                  description: Идентификатор пользователя
                medicine_name:
                  type: string
                  description: Название лекарства
                frequency:
                  type: integer
                  minimum: 1
                  maximum: 24
                  description: Количество приемов в день
                duration:
                  type: integer
                  minimum: 1
                  description: Длительность курса в днях
      responses:
        '200':
          description: Расписание успешно создано
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedule_id:
                    type: string
                    format: uuid
        '400':
          description: Некорректные параметры запроса
    get:
      summary: Получение деталей расписания
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: schedule_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Детали расписания
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  user_id:
                    type: string
                  medicine_name:
                    type: string
                  frequency:
                    type: integer
                  duration:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  taking_times:
                    type: array
                    items:
                      type: object
                      properties:
                        hour:
                          type: integer
                        minute:
                          type: integer
        '404':
          description: Расписание не найдено

  /next_takings:
    get:
      summary: Получение списка ближайших приемов лекарств
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список ближайших приемов
          content:
            application/json:
              schema:
                type: object
                properties:
                  takings:
                    type: array
                    items:
                      type: object
                      properties:
                        schedule_id:
                          type: string
                          format: uuid
                        medicine_name:
                          type: string
                        next_taking_time:
                          type: object
                          properties:
                            hour:
                              type: integer
                            minute:
                              type: integer 